### ISSUE TITLE
Publish an initial Parsec release process

### ISSUE THREAD

**Issue by hug-dev** [parallaxsecond/parsec-book#112]
*See the community meeting [minutes](https://github.com/parallaxsecond/community/blob/main/minutes/2021-04-27.md) for details.*

It was decided during last community meeting that we need to start having a process around Parsec service and Parsec Tool releases. This issue is about creating a document, published in the book, that will describe our release process:
- what do we release? The process could cover the Parsec service and the Parsec tool. However, packaging requirements for distro might mean that we have to have a matching dependency tree for those two components which might imply also releasing other dependent crates. 
- what is our release cadence? We could start with a 6 months cadence with the `0.8.0` release mid-september. That would be the last `0.x.y` release before `1.0.0`.
- what is our branching strategy? We need to give some time between branching and actual releasing for people (distro packagers essentially) to test the release candidate. During that time, bug/security fixes can still be applied but ideally no major functionality. The timings need to be described in the project. The release-stabilisation time is also a good moment to do more testing, like manual tests on real-hardware (those which can not be done on CI).

**Comment by paulhowardarm** [comment]
This was done a while ago. Should we just close this issue? @hug-dev

**Comment by hug-dev** [comment]
Yes! The Release process is live [here](https://parallaxsecond.github.io/parsec-book/contributing/release_process.html). It will be updated with our first release which checklist is [here](https://github.com/parallaxsecond/parsec/discussions/478).
