### ISSUE TITLE
Add more information about setting up the environment

### ISSUE THREAD

**Issue by ionut-arm** [parallaxsecond/parsec-book#13]
Currently there is an assumption that any engineers working on Parsec use it on Linux and have the dependencies sorted out, however a more thorough explanation of all the toolchains, utilities and libraries that are required is needed, including for MacOS.

There should definitely be some push towards using Docker for testing if anything fails, as that should be fairly painless.

Also, we need to improve the documentation about compiling the service correctly in order to use all the providers.

**Comment by hug-dev** [comment]
I added some info about how to test the TPM/PKCS11 providers [there](https://parallaxsecond.github.io/parsec-book/parsec_service/test.html#testing-the-tpm-provider-using-the-software-tpm). Is that enough for this issue?
