### ISSUE TITLE
Update code owners

### ISSUE THREAD

**Issue by ionut-arm** [parallaxsecond/parsec-book#155]
At the moment it's just myself and @hug-dev written down as [code owners](https://github.com/parallaxsecond/parsec-book/blob/main/.github/CODEOWNERS) for the book. We should probably expand that list now - @gowthamsk-arm, @mohamedasaker-arm, would you be up for that?

**Comment by gowthamsk-arm** [comment]
Yes. Happy to raise an MR for that.
