### ISSUE TITLE
Update operation docs

### ISSUE THREAD

**Issue by ionut-arm** [parallaxsecond/parsec-book#18]
Following the recent update of the operations to match the PSA crypto v1.0 spec, the documentation pages on operations are now obsolete. These should be updated as well.

Other items to review are: 
* what each operation can return as a response code
* what the return values are for each operation
* how the more complex input fields should be formatted
* a more detailed explanation of the key attributes structure

**Comment by hug-dev** [comment]
With parallaxsecond/parsec-interface-rs#30, there will be a stricter separation between PSA structures and Parsec internal ones. We should make sure that the PSA Crypto API contracts are respected: specific PSA errors codes should be returned for specific inputs.

**Comment by hug-dev** [comment]
#23 was merged
