### ISSUE TITLE
Make sure mitigations are documented properly

### ISSUE THREAD

**Issue by ionut-arm** [parallaxsecond/parsec-book#33]
For the service threat model: document thoroughly all the operational mitigations and the risks and limitations due to unmitigations.

Give recommendations and examples around how to set up the environment to provide sufficient security, including:
- Security Module rules (e.g. SELinux, SMACK) that could be used to protect access to the data stores, IPC communications and hardware providers
- Minimal Capabilities required, seccomp rules, etc. for the PARSEC service process
- Recommendations for use of encrypted file systems

**Comment by hug-dev** [comment]
For mitigations: a "Details" column was added [here](https://parallaxsecond.github.io/parsec-book/threat_model/threat_model.html#mitigations) linking with the appropriate issue.

For unmitigations: a [consequences](https://parallaxsecond.github.io/parsec-book/threat_model/threat_model.html#unmitigations) column was added.

For operational mitigations, the "Recommendations for a secure Parsec deployment" [guide](https://parallaxsecond.github.io/parsec-book/threat_model/secure_deployment.html) was added and should cover most point. A PR is needed though to link both page better.

I think the advanced security features listed in this issue could be looked at separate issues in the future.
