### ISSUE TITLE
Document existing tests

### ISSUE THREAD

**Issue by ionut-arm** [parallaxsecond/parsec-book#35]
We could add a page in our documentation with all our integration, E2E and maybe unit tests, with a short description for each one. This will let anyone interested see what exactly we test for and maybe raise some questions when some testing is missing.

**Comment by hug-dev** [comment]
That should actually be done as part of implementing mitigation 5 of our [threat model](https://parallaxsecond.github.io/parsec-book/threat_model/threat_model.html#mitigations):

> Parsec is coded with safety in mind and is tested extensively (TODO: add a link of test document describing the tests that we do in high-level terms on what platform).

**Comment by hug-dev** [comment]
I am wondering in what detail we need to go in that list as we don't want to change it often. For example, what if we rename one test, or make a little change of what it does?
If we stay high-level, that might be easier to maintain.
