### ISSUE TITLE
Simplify Parsec onboarding

### ISSUE THREAD

**Issue by hug-dev** [parallaxsecond/parsec-book#89]
A lot of new members, interested by the Parsec idea, come and ask "Cool, so how do I get started?"

We can not expect people to conscientiously go through all of the book to get an idea of what Parsec is and how it is working. I propose that we write a new top-level sections (maybe in place of "Parsec for users") with the name "Getting started!" or something similar. This section would be the entrypoint we would send to anyone new to the project.

The goal would be to guide them through simple steps to have a Parsec service running and do some commands on the client side. It will help them having a global idea of what Parsec is and then we can point them to more advanced steps: running on real hardware, securely installing the service, advanced client libraries, customised configuration, etc...

I propose the following structure (I took example from the [SPIRE guide](https://spiffe.io/docs/latest/try/getting-started-linux-macos-x/)). Those should probably be split amoung different sub-pages for clarity.

# Getting Started!

## Overview

Explaining what we are going to do: running the parsec service + doing client commands

## Prerequisites

Should be as low as possible.

## Running the Parsec service

Multiple options there, depending on the providers:
* Mbed Crypto natively (the easiest)
* TPM provider in a Docker container
* PKCS11 provider in a Docker container

## Making Parsec requests

Multiple options as well:
* using the Parsec tool (signing something for ex.)
* performing end to end tests

## Next steps

* Check the Parsec clients (Rust, Go, C)
* Check how to install Parsec securely
* Try Parsec on real-HW providers
* Watch a Parsec conference, read the rest of the book!

We already have most of the information but it is scattered through our book.
We would delete the "How to build and run Parsec guide" after that.

Our "How to test Parsec" needs to be revised as well, and I am not sure if it makes sense. Testing Parsec locally is harder and harder because it depends of specific configurations.

**Comment by hug-dev** [comment]
It was discussed that, to make it faster to get started, we could ship in Parsec releases a binary of Parsec, the parsec-tool and configuration files so that people can just execute them. This is similar as what SPIRE is doing.
The binary can first be compiled for Linux on x86 but can expend later. The binary would contain Parsec and the Mbed Crypto provider so that there is no dependency needed on the system.

Also, we should provider a Dockerfile containing all needed dependencies of Parsec (+ virtual TPM and HSM) so that people can try that as well.

**Comment by hug-dev** [comment]
> Also, we should provider a Dockerfile containing all needed dependencies of Parsec (+ virtual TPM and HSM) so that people can try that as well.

See [this](https://github.com/parallaxsecond/parsec/pull/357).

**Comment by hug-dev** [comment]
Here is what I think we could do.
We would use the GitHub "Releases" feature to ship two quickstart/demo pack versions. A pack would contain:
- a Parsec service binary
- a configuration file
- a `parsec-tool` binary
- (in the future) Rust and Go client examples

The pack would be using the `.tar.gz` format.

The first version would target Linux on x86. The parsec service would contain the Mbed Crypto provider with the Unix Peer Crendentials authenticator. The configuration file would configure the socket and the mappings to be inside this folder.

The second version would target the [`parsec-service-test-all`](https://github.com/orgs/parallaxsecond/packages/container/package/parsec-service-test-all) container. It would contain a Parsec service binary with all providers and all authenticators.

The guide would be:
- (2nd version only) Start docker: `docker run ... /bin/sh`
- download and extract the pack: `curl ... | tar ....`
- `cd` into the pack
- (2nd version only) Start tmux with two windows
- On one terminal, start Parsec: `./parsec`
- On the other terminal, configure the endpoint address: `export PARSEC_SERVICE_ENDPOINT = ...`
- On the other terminal, try some `parsec-tool` commands
- (in the future) Run and browse the Rust and Go client examples

**Comment by ionut-arm** [comment]
I sort of understand the reasoning behind the 2nd version - I have an idea for either an alternative, or for a 3rd version: a published container image that has Parsec correctly set up already - you spin it up and the `parsec` binary and config file are in the recommended locations (and the binary is on `$PATH`), the `/run/parsec` folder is set up, the `parsec-tool` is in `/usr/local/bin`... The guide can then go through looking at the paths, reading the config file and then playing around with the tool - maybe having a second user created as well, and using the `UnixPeerCredentialsAuthenticator`.

We could release that image tagged with the same version numbers as the service.

Does this sound too complicated?

**Comment by hug-dev** [comment]
That would simplify the process a bit further, we could have a third image. However I think I would prefer my version if we were to just choose one for 2:
- the installation steps are not that complicated: 3 or 4 commands
- a standard Parsec installation is not possible as systemd is not accessible inside docker container
- symmetrically to 1 we could also ship a small docker container for 1. that contains everything set up in the same way
- maybe it's easier to upload new releases' packs rather than update docker images?

**Comment by ionut-arm** [comment]
I think focusing on the goal is the most important - if the goal is how you defined in the first comment above:

> The goal would be to guide them through simple steps to have a Parsec service running and do some commands on the client side. It will help them having a global idea of what Parsec is and then we can point them to more advanced steps: running on real hardware, securely installing the service, advanced client libraries, customised configuration, etc...

then I'd say the examples should have little to no setup requirement for the service - it should just work out of the box. If we have a container that is all set up, we get that for free, just a `docker run -it ... /bin/bash` is needed.

> a standard Parsec installation is not possible as systemd is not accessible inside docker container

While that's technically true, you can actually obtain something similar by simply putting the commands to startup the service as a background task when a new shell is created, e.g. putting the relevant commands in `/etc/profile`. Then when the container starts you are good to go!

Another problem is that the `parsec-service-test-all` image is quite unfriendly, doesn't have many things that you might expect in a docker image for convenience (`vim`?).

**Comment by ionut-arm** [comment]
Also - should we have any guide/release for an Arm target (e.g. RaspberryPi or something like that?)

**Comment by hug-dev** [comment]
Yes I agree in principle although going through Docker might also be painful for some people: if you don't have it you have a lot of pre-work to do.
I agree though that since case 2. is already a container we could expand in a new one what is needed to already have a Parsec service there. I am not sure though how to make it include the configuration file that we want + examples of Go and Rust clients.

**Comment by ionut-arm** [comment]
> Yes I agree in principle although going through Docker might also be painful for some people: if you don't have it you have a lot of pre-work to do.

Definitely not as much work as you'd need to do to set up your environment to have all the providers available, though maybe we could just have instructions for one of them (PKCS11 or TPM).

> I am not sure though how to make it include the configuration file that we want + examples of Go and Rust clients.

The configuration is easy, we already do something like that for running the tests. Examples of Go/Rust clients - I wouldn't know, don't know what you'd do with those clients or if you just want to offer the potential users an easy framework to develop their own stuff.

It would be nice if we could have a release `.tar` that you can just extract and run and everything is fine... But we do have the guide for a secure setup, maybe that should be the "level 3" guide
