### ISSUE TITLE
General update of the book

### ISSUE THREAD

**Issue by hug-dev** [parallaxsecond/parsec-book#90]
I have spotted a few things that need updating on the book, feel free to add more:

- [x] alignment of bullet points in the description of [keys](https://parallaxsecond.github.io/parsec-book/parsec_client/operations/psa_export_public_key.html)
- [ ] add documentation about the new providers
- [ ] the [dataflow diagram](https://parallaxsecond.github.io/parsec-book/parsec_service/interfaces_and_dataflow.html#data-flow-diagram) still refers to `KeyIDManager` instead of `KeyInfoManager`
- [ ] cross-compilation information
- [ ] code coverage information
- [ ] authenticators were added to features

**Comment by hug-dev** [comment]
@ionut-arm Should we add the `KeyInfoManagerClient` in the diagrams?

**Comment by ionut-arm** [comment]
I don't think so, it's more of a convenience layer that does some interfacing between KIM and providers
